/*
 * Copyright 2013 ragnar0k@fabytes.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package manniac;

/**
 *
 * @author ragnar0k@fabytes.com
 */


import java.text.DecimalFormat;
import javax.swing.JList;

public class ThreshEdit extends javax.swing.JFrame implements Runnable {
    String net;
    String type;
    String thres;
    String start;
    String end;
    SQLiteLib sql;
    double mp;
    EditNet main;
    
    public void run() {
        this.setVisible(true);
    }
    

    
    
    /**
     * Creates new form NewJFrame
     */
    public ThreshEdit(EditNet vader, boolean showFileType, String nnet, String fileType, String thresholds, SQLiteLib sqlClass) {
        initComponents();
        if (!showFileType) 
            FTPanel.setVisible(false);
        else 
            lastPlus.setVisible(false);
        start = "";
        end = "";
        net = nnet;
        type = fileType;
        thres = thresholds;
        sql = sqlClass;
        main = vader;
        mp = 0;
        if (thresholds.length() > 0) {
            String[] thstuff = thresholds.split("\\s");
            String[] values = thstuff[1].split("-");
            StartValue.setText(values[0]);
            EndValue.setText(values[1]);
            ScoreBox.setText(thstuff[3]);
            WeightBox.setText(thstuff[5]);
            FileType.setText(fileType);
            start = values[0];
            end = values[1];
        }
    }

    private Double hashDbl(Double dbl) {
        DecimalFormat df = new DecimalFormat("#0.00000");
        String tmp = df.format(dbl);
        return Double.valueOf(tmp);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FTPanel = new javax.swing.JPanel();
        FileType = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StartValue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EndValue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        WeightBox = new javax.swing.JTextField();
        ScoreBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Send = new javax.swing.JButton();
        mouseEnd = new javax.swing.JButton();
        mouseStart = new javax.swing.JButton();
        lastPlus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("FileType");

        javax.swing.GroupLayout FTPanelLayout = new javax.swing.GroupLayout(FTPanel);
        FTPanel.setLayout(FTPanelLayout);
        FTPanelLayout.setHorizontalGroup(
            FTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(FileType, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FTPanelLayout.setVerticalGroup(
            FTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setText("Start Threshold value");

        jLabel3.setText("End Threshold value");

        jLabel4.setText("Weight");

        jLabel5.setText("Score");

        Send.setText("Send");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });

        mouseEnd.setText("Last mouse click");
        mouseEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouseEndActionPerformed(evt);
            }
        });

        mouseStart.setText("Last mouse click");
        mouseStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouseStartActionPerformed(evt);
            }
        });

        lastPlus.setText("Last value + 0.00001");
        lastPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastPlusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(FTPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(StartValue, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mouseStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(Send, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(WeightBox)
                                    .addComponent(ScoreBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EndValue, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mouseEnd)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FTPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(StartValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mouseStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastPlus)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EndValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mouseEnd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WeightBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScoreBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(Send)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        if (start.length() > 0 && end.length() > 0)
            sql.deleteSingleThreshold(type, net, start, end);
        if (type.length() == 0)
            type = FileType.getText();
        sql.addSingleThreshold(net, type, StartValue.getText() , EndValue.getText(), WeightBox.getText(), ScoreBox.getText());
        try {
        main.populateList();
        }
        catch (Exception exc) {
            System.out.println(exc.toString());
        }
        this.dispose();
    }//GEN-LAST:event_SendActionPerformed

    private void mouseStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouseStartActionPerformed
        double[] mloc = main.getMouseLocation();
        StartValue.setText(String.valueOf(hashDbl(mloc[0])));
    }//GEN-LAST:event_mouseStartActionPerformed

    private void mouseEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouseEndActionPerformed
        double[] mloc = main.getMouseLocation();
        EndValue.setText(String.valueOf(hashDbl(mloc[0])));    }//GEN-LAST:event_mouseEndActionPerformed

    private void lastPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastPlusActionPerformed
        String[] thresh = sql.GetThresholds(net, type);
        String last = thresh[thresh.length - 1];
        String[] tmp = last.split(",");
        StartValue.setText(String.valueOf(Double.valueOf(tmp[1]) + 0.00001));
    }//GEN-LAST:event_lastPlusActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void setMousePoint(double mousePoint)
    {
        mp = mousePoint;
    }
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreshEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreshEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreshEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreshEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ///new ThreshEdit().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EndValue;
    private javax.swing.JPanel FTPanel;
    private javax.swing.JTextField FileType;
    private javax.swing.JTextField ScoreBox;
    private javax.swing.JButton Send;
    private javax.swing.JTextField StartValue;
    private javax.swing.JTextField WeightBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton lastPlus;
    private javax.swing.JButton mouseEnd;
    private javax.swing.JButton mouseStart;
    // End of variables declaration//GEN-END:variables
}
